import { ChainConfig } from "../../models/Chain";
import { getChainRpcUrl } from "./rpcs";

export type ChainType = "near" | "sol" | "evm" | "tron" | "aptos" | "ton" | "sui";

export const chainTypes: Record<ChainType, { value: string; name: string; color: string; bg: string; bgColor: string; }> = {
  near: {
    value: "near",
    name: "Near",
    color: "#56DEAD",
    bgColor: "#01ED97",
    bg: "linear-gradient(90deg, rgba(1, 237, 151, 0.20) 0%, rgba(1, 237, 151, 0.00) 50%)",
  },
  sol: {
    value: "sol",
    name: "Solana",
    color: "#987FF3",
    bgColor: "#282C34",
    bg: "linear-gradient(90deg, rgba(248, 108, 255, 0.20) 0%, rgba(248, 108, 255, 0.00) 50%)",
  },
  evm: {
    value: "evm",
    name: "EVM",
    color: "#C4CAE1",
    bgColor: "#6284F5",
    bg: "linear-gradient(90deg, rgba(185, 215, 255, 0.20) 0%, rgba(185, 215, 255, 0.00) 50%)",
  },
  tron: {
    value: "tron",
    name: "Tron",
    color: "#F66273",
    bgColor: "#D21F10",
    bg: "linear-gradient(90deg, rgba(210, 31, 16, 0.20) 0%, rgba(210, 31, 16, 0.00) 50%)",
  },
  aptos: {
    value: "aptos",
    name: "Aptos",
    color: "#000000",
    bgColor: "#000000",
    bg: "linear-gradient(90deg, rgba(0, 0, 0, 0.20) 0%, rgba(0, 0, 0, 0.00) 50%)",
  },
  ton: {
    value: "ton",
    name: "Ton",
    color: "#0098EA",
    bgColor: "#298DFF",
    bg: "linear-gradient(90deg, rgba(0, 152, 234, 0.20) 0%, rgba(0, 152, 234, 0.00) 50%)",
  },
  sui: {
    value: "sui",
    name: "Sui",
    color: "#298DFF",
    bgColor: "#298DFF",
    bg: "linear-gradient(90deg, rgba(41, 141, 255, 0.20) 0%, rgba(0, 152, 234, 0.00) 50%)",
  },
};

/**
 * You should configure the chain images yourself
 * @param {string} name chain name
 * @returns {string}
 */
const getStableflowChainLogo = (name: string) => {
  return `/chains/${name}.png`;
};

const chains: Record<string, ChainConfig> = {
  near: {
    chainName: "Near",
    blockchain: "near",
    chainIcon: getStableflowChainLogo("near"),
    chainIconGray: getStableflowChainLogo("near-gray"),
    chainType: chainTypes.near.value,
    blockExplorerUrl: "https://nearblocks.io/txns",
    blockExplorerUrls: ["https://nearblocks.io"],
    primaryColor: "#76EA9E",
    nativeToken: {
      symbol: "NEAR",
      decimals: 24,
    },
    ...getChainRpcUrl("near"),
  },
  sol: {
    chainName: "Solana",
    blockchain: "sol",
    chainIcon: getStableflowChainLogo("solana"),
    chainIconGray: getStableflowChainLogo("solana-gray"),
    chainType: chainTypes.sol.value,
    blockExplorerUrl: "https://solscan.io/tx",
    blockExplorerUrls: ["https://solscan.io"],
    primaryColor: "#B93EF0",
    nativeToken: {
      symbol: "SOL",
      decimals: 9,
    },
    ...getChainRpcUrl("sol"),
  },
  eth: {
    chainName: "Ethereum",
    blockchain: "eth",
    chainIcon: getStableflowChainLogo("Ethereum"),
    chainIconGray: getStableflowChainLogo("Ethereum-gray"),
    chainType: chainTypes.evm.value,
    chainId: 1,
    blockExplorerUrl: "https://etherscan.io/tx",
    blockExplorerUrls: ["https://etherscan.io"],
    primaryColor: "#7083ee",
    nativeToken: {
      symbol: "ETH",
      decimals: 18,
    },
    ...getChainRpcUrl("eth"),
  },
  arb: {
    chainName: "Arbitrum",
    blockchain: "arb",
    chainIcon: getStableflowChainLogo("Arbitrum"),
    chainIconGray: getStableflowChainLogo("Arbitrum-gray"),
    chainType: chainTypes.evm.value,
    chainId: 42161,
    blockExplorerUrl: "https://arbiscan.io/tx",
    blockExplorerUrls: ["https://arbiscan.io"],
    primaryColor: "#4763A7",
    nativeToken: {
      symbol: "ETH",
      decimals: 18,
    },
    ...getChainRpcUrl("arb"),
  },
  bsc: {
    chainName: "BNB Chain",
    blockchain: "bsc",
    chainIcon: getStableflowChainLogo("bsc"),
    chainIconGray: getStableflowChainLogo("bsc-gray"),
    chainType: chainTypes.evm.value,
    chainId: 56,
    blockExplorerUrl: "https://bscscan.com/tx",
    blockExplorerUrls: ["https://bscscan.com"],
    primaryColor: "#F1C144",
    nativeToken: {
      symbol: "BNB",
      decimals: 18,
    },
    ...getChainRpcUrl("bsc"),
  },
  avax: {
    chainName: "Avalanche",
    blockchain: "avax",
    chainIcon: getStableflowChainLogo("Avalanche"),
    chainIconGray: getStableflowChainLogo("Avalanche-gray"),
    chainType: chainTypes.evm.value,
    chainId: 43114,
    blockExplorerUrl: "https://snowtrace.io/tx",
    blockExplorerUrls: ["https://snowtrace.io"],
    primaryColor: "#9D2620",
    nativeToken: {
      symbol: "AVAX",
      decimals: 18,
    },
    ...getChainRpcUrl("avax"),
  },
  base: {
    chainName: "Base",
    blockchain: "base",
    chainIcon: getStableflowChainLogo("Base"),
    chainIconGray: getStableflowChainLogo("Base-gray"),
    chainType: chainTypes.evm.value,
    chainId: 8453,
    blockExplorerUrl: "https://basescan.org/tx",
    blockExplorerUrls: ["https://basescan.org"],
    primaryColor: "#3137F6",
    nativeToken: {
      symbol: "ETH",
      decimals: 18,
    },
    ...getChainRpcUrl("base"),
  },
  pol: {
    chainName: "Polygon",
    blockchain: "pol",
    chainIcon: getStableflowChainLogo("Polygon"),
    chainIconGray: getStableflowChainLogo("Polygon-gray"),
    chainType: chainTypes.evm.value,
    chainId: 137,
    blockExplorerUrl: "https://polygonscan.com/tx",
    blockExplorerUrls: ["https://polygonscan.com"],
    primaryColor: "#5A2AD1",
    nativeToken: {
      symbol: "POL",
      decimals: 18,
    },
    ...getChainRpcUrl("pol"),
  },
  gnosis: {
    chainName: "Gnosis",
    blockchain: "gnosis",
    chainIcon: getStableflowChainLogo("Gnosis"),
    chainIconGray: getStableflowChainLogo("Gnosis-gray"),
    chainType: chainTypes.evm.value,
    chainId: 100,
    blockExplorerUrl: "https://gnosisscan.io/tx",
    blockExplorerUrls: ["https://gnosisscan.io"],
    primaryColor: "#285230",
    nativeToken: {
      symbol: "XDAI",
      decimals: 18,
    },
    ...getChainRpcUrl("gnosis"),
  },
  op: {
    chainName: "Optimism",
    blockchain: "op",
    chainIcon: getStableflowChainLogo("Optimism"),
    chainIconGray: getStableflowChainLogo("Optimism-gray"),
    chainType: chainTypes.evm.value,
    chainId: 10,
    blockExplorerUrl: "https://optimistic.etherscan.io/tx",
    blockExplorerUrls: ["https://optimistic.etherscan.io"],
    primaryColor: "#B5271D",
    nativeToken: {
      symbol: "ETH",
      decimals: 18,
    },
    ...getChainRpcUrl("op"),
  },
  tron: {
    chainName: "Tron",
    blockchain: "tron",
    chainIcon: getStableflowChainLogo("Tron"),
    chainIconGray: getStableflowChainLogo("Tron-gray"),
    chainType: chainTypes.tron.value,
    blockExplorerUrl: "https://tronscan.org/#/transaction",
    blockExplorerUrls: ["https://tronscan.org"],
    primaryColor: "#BC3221",
    nativeToken: {
      symbol: "TRX",
      decimals: 6,
    },
    ...getChainRpcUrl("tron"),
  },
  aptos: {
    chainName: "Aptos",
    blockchain: "aptos",
    chainIcon: getStableflowChainLogo("Aptos"),
    chainIconGray: getStableflowChainLogo("Aptos-gray"),
    chainType: chainTypes.aptos.value,
    blockExplorerUrl: "https://aptoscan.com/transaction",
    blockExplorerUrls: ["https://aptoscan.com"],
    primaryColor: "#000000",
    nativeToken: {
      symbol: "APT",
      decimals: 8,
    },
    ...getChainRpcUrl("aptos"),
  },
  bera: {
    chainName: "Berachain",
    blockchain: "bera",
    chainIcon: getStableflowChainLogo("Berachain"),
    chainIconGray: getStableflowChainLogo("Berachain-gray"),
    chainType: chainTypes.evm.value,
    chainId: 80094,
    blockExplorerUrl: "https://berascan.com/tx/",
    blockExplorerUrls: ["https://berascan.com"],
    primaryColor: "#F37325",
    nativeToken: {
      symbol: "BERA",
      decimals: 18,
    },
    ...getChainRpcUrl("bera"),
  },
  xlayer: {
    chainName: "X Layer",
    blockchain: "xlayer",
    chainIcon: getStableflowChainLogo("xlayer"),
    chainIconGray: getStableflowChainLogo("xlayer-gray"),
    chainType: chainTypes.evm.value,
    chainId: 196,
    blockExplorerUrl: "https://www.oklink.com/xlayer/tx/",
    blockExplorerUrls: ["https://www.oklink.com"],
    primaryColor: "#000000",
    nativeToken: {
      symbol: "OKB",
      decimals: 18,
    },
    ...getChainRpcUrl("xlayer"),
  },
  plasma: {
    chainName: "Plasma",
    blockchain: "plasma",
    chainIcon: getStableflowChainLogo("Plasma"),
    chainIconGray: getStableflowChainLogo("Plasma-gray"),
    chainType: chainTypes.evm.value,
    chainId: 9745,
    blockExplorerUrl: "https://plasmascan.to/tx/",
    blockExplorerUrls: ["https://plasmascan.to"],
    primaryColor: "#162F29",
    nativeToken: {
      symbol: "XPL",
      decimals: 18,
    },
    ...getChainRpcUrl("plasma"),
  },
  ton: {
    chainName: "Ton",
    blockchain: "ton",
    chainIcon: getStableflowChainLogo("Ton"),
    chainIconGray: getStableflowChainLogo("Ton-gray"),
    chainType: chainTypes.ton.value,
    blockExplorerUrl: "https://tonviewer.com/transaction/",
    blockExplorerUrls: ["https://tonviewer.com"],
    primaryColor: "#0098EA",
    nativeToken: {
      symbol: "TON",
      decimals: 9,
    },
    ...getChainRpcUrl("ton"),
  },
  mantle: {
    chainName: "Mantle",
    blockchain: "mantle",
    chainIcon: getStableflowChainLogo("Mantle"),
    chainIconGray: getStableflowChainLogo("Mantle-gray"),
    chainType: chainTypes.evm.value,
    chainId: 5000,
    blockExplorerUrl: "https://mantlescan.xyz/tx/",
    blockExplorerUrls: ["https://mantlescan.xyz"],
    primaryColor: "#162F29",
    nativeToken: {
      symbol: "MNT",
      decimals: 18,
    },
    ...getChainRpcUrl("mantle"),
  },
  megaeth: {
    chainName: "MegaETH",
    blockchain: "megaeth",
    chainIcon: getStableflowChainLogo("MegaETH"),
    chainIconGray: getStableflowChainLogo("MegaETH-gray"),
    chainType: chainTypes.evm.value,
    chainId: 4326,
    blockExplorerUrl: "https://mega.etherscan.io/tx/",
    blockExplorerUrls: ["https://mega.etherscan.io"],
    primaryColor: "#19191A",
    nativeToken: {
      symbol: "ETH",
      decimals: 18,
    },
    ...getChainRpcUrl("megaeth"),
  },
  ink: {
    chainName: "Ink",
    blockchain: "ink",
    chainIcon: getStableflowChainLogo("Ink"),
    chainIconGray: getStableflowChainLogo("Ink-gray"),
    chainType: chainTypes.evm.value,
    chainId: 57073,
    blockExplorerUrl: "https://explorer.inkonchain.com/tx/",
    blockExplorerUrls: ["https://explorer.inkonchain.com"],
    primaryColor: "#7132F5",
    nativeToken: {
      symbol: "ETH",
      decimals: 18,
    },
    ...getChainRpcUrl("ink"),
  },
  stable: {
    chainName: "Stable",
    blockchain: "stable",
    chainIcon: getStableflowChainLogo("Stable"),
    chainIconGray: getStableflowChainLogo("Stable-gray"),
    chainType: chainTypes.evm.value,
    chainId: 988,
    blockExplorerUrl: "https://uniscan.xyz/tx/",
    blockExplorerUrls: ["https://uniscan.xyz"],
    primaryColor: "#01241D",
    nativeToken: {
      symbol: "USDT0",
      decimals: 18,
    },
    ...getChainRpcUrl("stable"),
  },
  celo: {
    chainName: "Celo",
    blockchain: "celo",
    chainIcon: getStableflowChainLogo("Celo"),
    chainIconGray: getStableflowChainLogo("Celo-gray"),
    chainType: chainTypes.evm.value,
    chainId: 42_220,
    blockExplorerUrl: "https://celoscan.io/tx/",
    blockExplorerUrls: ["https://celoscan.io"],
    primaryColor: "#FCFF52",
    nativeToken: {
      symbol: "CELO",
      decimals: 18,
    },
    ...getChainRpcUrl("celo"),
  },
  sei: {
    chainName: "Sei",
    blockchain: "sei",
    chainIcon: getStableflowChainLogo("Sei"),
    chainIconGray: getStableflowChainLogo("Sei-gray"),
    chainType: chainTypes.evm.value,
    chainId: 1329,
    blockExplorerUrl: "https://seitrace.com/tx/",
    blockExplorerUrls: ["https://seitrace.com"],
    primaryColor: "#991717",
    nativeToken: {
      symbol: "SEI",
      decimals: 18,
    },
    ...getChainRpcUrl("sei"),
  },
  flare: {
    chainName: "Flare",
    blockchain: "flare",
    chainIcon: getStableflowChainLogo("Flare"),
    chainIconGray: getStableflowChainLogo("Flare-gray"),
    chainType: chainTypes.evm.value,
    chainId: 14,
    blockExplorerUrl: "https://flare-explorer.flare.network/tx/",
    blockExplorerUrls: ["https://flare-explorer.flare.network"],
    primaryColor: "#E62058",
    nativeToken: {
      symbol: "FLR",
      decimals: 18,
    },
    ...getChainRpcUrl("flare"),
  },
  frax: {
    chainName: "Fraxtal",
    blockchain: "frax",
    chainIcon: getStableflowChainLogo("Frax"),
    chainIconGray: getStableflowChainLogo("Frax-gray"),
    chainType: chainTypes.evm.value,
    chainId: 252,
    blockExplorerUrl: "https://fraxscan.com/tx/",
    blockExplorerUrls: ["https://fraxscan.com"],
    primaryColor: "#000",
    nativeToken: {
      symbol: "FRAX",
      decimals: 18,
    },
    ...getChainRpcUrl("frax"),
  },
  sui: {
    chainName: "Sui",
    blockchain: "sui",
    chainIcon: getStableflowChainLogo("Sui"),
    chainIconGray: getStableflowChainLogo("Sui-gray"),
    chainType: chainTypes.sui.value,
    blockExplorerUrl: "https://suiscan.xyz/mainnet/tx",
    blockExplorerUrls: ["https://suiscan.xyz/mainnet"],
    primaryColor: "#298DFF",
    nativeToken: {
      symbol: "SUI",
      decimals: 9,
    },
    ...getChainRpcUrl("sui"),
  },
  katana: {
    chainName: "Katana",
    blockchain: "katana",
    chainIcon: getStableflowChainLogo("Katana"),
    chainIconGray: getStableflowChainLogo("Katana-gray"),
    chainType: chainTypes.evm.value,
    chainId: 747474,
    blockExplorerUrl: "https://katanascan.com/tx",
    blockExplorerUrls: ["https://katanascan.com"],
    primaryColor: "#F6FF0D",
    nativeToken: {
      symbol: "ETH",
      decimals: 18,
    },
    ...getChainRpcUrl("katana"),
  },
};

export default chains;
